apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: movie-service
    visualize: "true"
  name: movie-service
spec:
  externalIPs:
  - 192.168.1.51
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8080
  selector:
    run: movie-service
    visualize: "true"
status:
  loadBalancer: {}