apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: preference-service
    visualize: "true"
  name: preference-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: preference-service
    visualize: "true"
status:
  loadBalancer: {}