apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ui
    visualize: "true"
  name: ui
spec:
  deprecatedPublicIPs:
  - 192.168.1.51
  externalIPs:
  - 192.168.1.51
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: ui
    visualize: "true"
status:
  loadBalancer: {}